"""T77: the research module's two tables, in the `research` schema.

`trials` and `paper_candidates`, ported from EdgeLab's SQLite registry. T76 created the empty
`research` namespace and the `quantdesk_ro` grants that cover it; this fills it. Because T76
set `ALTER DEFAULT PRIVILEGES`, both tables are readable by `quantdesk_ro` the moment they
exist -- no grant statement belongs in this file.

Autogenerated from `app.modules.research.models.db` and then read line by line, which is how
the missing `UTCDateTime` import below was caught: autogenerate emits the fully-qualified type
name it found on the column but does not add the import for it, so the generated file raised
`NameError` on `promoted_at`. See `alembic/env.py` for why the old `app.models.db` spelling
still resolves at all.

Data does not move here. The existing 134,377 trials are loaded afterwards by
`scripts/migrate_registry.py`, deliberately kept out of the migration chain: it is a one-shot
import from a file that lives on one laptop, it takes minutes, and it must be re-runnable and
verifiable on its own. A migration that silently did nothing on every other host would be the
worse design.

Revision ID: 27cf03abcbc1
Revises: a3f1c7d92b64
Create Date: 2026-09-19

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.modules.gex.models.db
from alembic import op

revision: str = "27cf03abcbc1"
down_revision: str | Sequence[str] | None = "a3f1c7d92b64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Matches `app.core.schemas.SCHEMA_RESEARCH`. Spelled literally rather than imported, for the
#: reason every revision spells things literally: this file records what was applied to a real
#: database, and must not change meaning when a constant is renamed later.
SCHEMA = "research"

#: `JSONB` on Postgres, `JSON` on SQLite -- the same variant the model declares. The tests run
#: offline against SQLite, where `JSONB` cannot be compiled at all.
_PARAMS_JSON = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")


def upgrade() -> None:
    op.create_table(
        "paper_candidates",
        sa.Column("hash", sa.String(length=24), nullable=False),
        sa.Column(
            "promoted_at",
            app.modules.gex.models.db.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("params", _PARAMS_JSON, nullable=False),
        sa.Column("promoted_oos_sharpe", sa.Float(), nullable=True),
        sa.Column("sharpe_2x", sa.Float(), nullable=True),
        sa.Column("neighbor_med", sa.Float(), nullable=True),
        sa.Column("wf_pos", sa.Integer(), nullable=True),
        sa.Column("wf_active", sa.Integer(), nullable=True),
        sa.Column("wf_med", sa.Float(), nullable=True),
        sa.Column("corr_max", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("hash"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_paper_candidates_promoted_at",
        "paper_candidates",
        ["promoted_at"],
        unique=False,
        schema=SCHEMA,
    )

    op.create_table(
        "trials",
        sa.Column("hash", sa.String(length=24), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("params", _PARAMS_JSON, nullable=False),
        sa.Column("is_sharpe", sa.Float(), nullable=True),
        sa.Column("is_cagr", sa.Float(), nullable=True),
        sa.Column("is_max_dd", sa.Float(), nullable=True),
        sa.Column("is_fills", sa.Integer(), nullable=True),
        sa.Column("oos_sharpe", sa.Float(), nullable=True),
        sa.Column("oos_cagr", sa.Float(), nullable=True),
        sa.Column("oos_max_dd", sa.Float(), nullable=True),
        sa.Column("oos_fills", sa.Integer(), nullable=True),
        sa.Column("oos_exposure", sa.Float(), nullable=True),
        sa.Column("oos_bars", sa.Integer(), nullable=True),
        sa.Column("oos_years", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("hash"),
        schema=SCHEMA,
    )
    # The SQLite registry's one index, carried over: it serves the leaderboard's
    # `ORDER BY oos_sharpe DESC LIMIT n`.
    op.create_index(
        "ix_trials_oos_sharpe",
        "trials",
        [sa.literal_column("oos_sharpe DESC")],
        unique=False,
        schema=SCHEMA,
    )
    # New here, and the reason the leaderboard stays fast at 134k rows and growing: the filters
    # run before the ordering.
    op.create_index(
        "ix_trials_filters", "trials", ["oos_fills", "oos_exposure"], unique=False, schema=SCHEMA
    )
    op.create_index("ix_trials_run_date", "trials", ["run_date"], unique=False, schema=SCHEMA)


def downgrade() -> None:
    op.drop_index("ix_trials_run_date", table_name="trials", schema=SCHEMA)
    op.drop_index("ix_trials_filters", table_name="trials", schema=SCHEMA)
    op.drop_index("ix_trials_oos_sharpe", table_name="trials", schema=SCHEMA)
    op.drop_table("trials", schema=SCHEMA)
    op.drop_index(
        "ix_paper_candidates_promoted_at", table_name="paper_candidates", schema=SCHEMA
    )
    op.drop_table("paper_candidates", schema=SCHEMA)
